# Generated by Django 4.2.8 on 2023-12-07 19:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('entrance', 'Входные'), ('royal', 'Царговые'), ('pvc', 'ПВХ'), ('veneer', 'Шпон'), ('laminate', 'Ламинат'), ('solid', 'Массив натуральный')], default=None, max_length=50, verbose_name='Выберите тип двери')),
                ('name', models.CharField(max_length=250, verbose_name='Название двери')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена двери')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание двери')),
            ],
            options={
                'verbose_name': 'Дверь',
                'verbose_name_plural': 'Двери',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=256, verbose_name='Размер двери')),
            ],
            options={
                'verbose_name': 'Размер двери',
                'verbose_name_plural': 'Размеры дверей',
                'ordering': ('size',),
            },
        ),
        migrations.CreateModel(
            name='DoorAlbumColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название цвета')),
                ('image', models.ImageField(upload_to='doors_color/', verbose_name='Фото')),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_color', to='products.door', verbose_name='Дверь')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DoorAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='doors/', verbose_name='Фото')),
                ('door', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_door', to='products.door', verbose_name='Дверь')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='door',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='door', to='products.size', verbose_name='Размеры двери'),
        ),
    ]
