# Generated by Django 4.2.8 on 2023-12-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотографии товара',
                'verbose_name_plural': 'Фотографии товаров',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductAlbumColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название цвета')),
                ('image', models.ImageField(upload_to='produst_color/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотографии расцветок товара',
                'verbose_name_plural': 'Фотографии расцветок товаров',
                'ordering': ('name',),
            },
        ),
        migrations.RenameModel(
            old_name='RelatedProducts',
            new_name='RelatedProduct',
        ),
        migrations.RemoveField(
            model_name='dooralbumcolor',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('None', '  '), ('royal', 'Царговые'), ('pvc', 'ПВХ'), ('veneer', 'Шпон'), ('laminate', 'Ламинат'), ('solid', 'Массив натуральный')], default=None, max_length=50, verbose_name='Выберите тип двери (для межкомнатных дверей)'),
        ),
        migrations.DeleteModel(
            name='DoorAlbum',
        ),
        migrations.DeleteModel(
            name='DoorAlbumColor',
        ),
        migrations.AddField(
            model_name='productalbumcolor',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_color', to='products.product', verbose_name='Дверь'),
        ),
        migrations.AddField(
            model_name='productalbum',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_door', to='products.product', verbose_name='Дверь'),
        ),
    ]
