# Generated by Django 4.2.8 on 2023-12-08 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productalbum_productalbumcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalbum',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_product', to='products.product', verbose_name='Дверь'),
        ),
    ]
