# Generated by Django 4.2.8 on 2023-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productalbum_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена товара по акции'),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='price_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена по акции'),
        ),
    ]
