# Generated by Django 4.2.8 on 2023-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price_discount_relatedproduct_price_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subproduct',
            field=models.ManyToManyField(blank=True, null=True, related_name='qwerty', to='products.product', verbose_name='Сопутка'),
        ),
    ]
