# Generated by Django 4.2.8 on 2023-12-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_subproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_order',
            field=models.BooleanField(default=True, verbose_name='Под заказ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('None', ' '), ('subproduct', 'Сопутствующие товары'), ('accessories', 'Фурнитура'), ('entrance_door', 'Входная дверь'), ('interior_door', 'Межкомнатная дверь'), ('window', 'Окно'), ('roller_shutters', 'Рольставни')], default=None, max_length=50, verbose_name='Выберите тип товара'),
        ),
        migrations.DeleteModel(
            name='RelatedProduct',
        ),
    ]
