# Generated by Django 4.2.8 on 2023-12-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_for_order_alter_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hit_sale',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
            preserve_default=False,
        ),
    ]
