# Generated by Django 4.2.8 on 2023-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_hit_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='Товар по акции'),
            preserve_default=False,
        ),
    ]
