# Generated by Django 4.2.8 on 2023-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('title',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена товара БЕЗ акции'),
        ),
    ]
