# Generated by Django 4.2.8 on 2023-12-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=255, verbose_name='Фамилия Имя')),
                ('telefone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('content', models.TextField(verbose_name='Содержимое письма')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на замер',
                'verbose_name_plural': 'Заявки на замер',
                'db_table': 'app_feedback',
                'ordering': ['-time_create'],
            },
        ),
    ]
