# Generated by Django 4.2.8 on 2023-12-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_requestformeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestformeasurement',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='requestformeasurement',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое письма'),
        ),
        migrations.AlterField(
            model_name='requestformeasurement',
            name='name_surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия Имя'),
        ),
    ]
