# Generated by Django 4.2.8 on 2024-01-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('None', ' '), ('subproduct', 'Сопутствующие товары'), ('accessories', 'Фурнитура'), ('entrance_door', 'Входная дверь'), ('interior_door', 'Межкомнатная дверь'), ('window', 'Окно'), ('roller_shutters', 'Рольставни'), ('mouldings', 'Погонаж')], default=None, max_length=50, verbose_name='Выберите тип товара'),
        ),
    ]
