# Generated by Django 4.2.8 on 2024-01-23 18:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_product',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Варианты цветов'),
        ),
    ]
