# Generated by Django 4.2.8 on 2024-01-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_productalbum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productalbum',
            options={'ordering': ('time_create', 'name'), 'verbose_name': 'Фотографии товара', 'verbose_name_plural': 'Фотографии товаров'},
        ),
        migrations.AlterModelOptions(
            name='productalbumcolor',
            options={'ordering': ('time_create', 'name'), 'verbose_name': 'Фотографии расцветок товара', 'verbose_name_plural': 'Фотографии расцветок товаров'},
        ),
    ]
