# Generated by Django 4.2.8 on 2024-01-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productalbum_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
