# Generated by Django 4.2.8 on 2024-01-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_article_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAlbumColor',
        ),
    ]
