# Generated by Django 4.2.8 on 2024-01-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_delete_productalbumcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='articles/', verbose_name='Фото'),
        ),
    ]
