# Generated by Django 4.2.8 on 2024-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='articles/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
