# Generated by Django 4.2.8 on 2024-06-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foto',
            field=models.ManyToManyField(related_name='foto', to='products.productalbum', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productalbum',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Название фото'),
        ),
    ]
