# Generated by Django 4.2.8 on 2024-06-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_foto_alter_productalbum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='foto',
        ),
    ]
